os: linux
dist: bionic
language: python
python: "3.7"

install:
  - pip install conan

before_script:
  - conan profile new default --detect

script:
  - mkdir build && cd build
  - conan install ..
  - cmake ..
  - cmake --build .
  - ctest
